name: verif
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch=2.1.2
  - pytorch::cpuonly
  - numpy<2
  - conda-forge::transformers=4.36.2
  - conda-forge::fastapi=0.109.0
  - conda-forge::uvicorn=0.27.0
  - conda-forge::pydantic=2.5.3
  - conda-forge::python-multipart=0.0.6
  - conda-forge::black=23.12.1
  - conda-forge::isort=5.13.2
  - conda-forge::flake8=7.0.0
  - conda-forge::mypy=1.8.0
  - conda-forge::pre-commit=3.6.0
  - conda-forge::pytest=7.4.3
  - conda-forge::pytest-cov=4.1.0
  - conda-forge::requests=2.31.0
  - pip
  - pip:
      - types-requests==2.31.0
      - datasets==2.16.1
      - tqdm==4.66.1
